apiVersion: flink.k8s.io/v1beta1
kind: FlinkApplication
metadata:
  name: wordcount-operator-example
  namespace: flink-operator
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9249'
  labels:
    environment: development
spec:
  image: lightbend/wordcount-operator-example:test
  imagePullPolicy: Always
  flinkConfig:
    taskmanager.heap.size: 200
    state.backend.fs.checkpointdir: file:///checkpoints/flink/checkpoints
    state.checkpoints.dir: file:///checkpoints/flink/externalized-checkpoints
    state.savepoints.dir: file:///checkpoints/flink/savepoints
  jobManagerConfig:
    resources:
      requests:
        memory: "200Mi"
        cpu: "0.2"
    replicas: 1
    serviceAccount: "imprecise-sasquatch-flink"
  taskManagerConfig:
    taskSlots: 2
    serviceAccount: "imprecise-sasquatch-flink"
    resources:
      requests:
        memory: "200Mi"
        cpu: "0.2"
  flinkVersion: "1.8"
  jarName: "WordCount.jar"
  parallelism: 3
  entryClass: "org.apache.flink.streaming.examples.wordcount.WordCount"
