apiVersion: flink.k8s.io/v1beta1
kind: FlinkApplication
metadata:
  name: operator-test-app
  annotations:
  labels:
    environment: development
spec:
  image: 127.0.0.1:3200/flink-test-app:local.1
  # image: operator-test-app:test1
  # image: lyft/operator-test-app:b1b3cb8e8f98bd41f44f9c89f8462ce255e0d13f.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: dockerhub
  flinkConfig:
#    jobmanager.memory.jvm-overhead.min: "50 mb"
#    jobmanager.memory.jvm-metaspace.size: "80 mb"
#    jobmanager.memory.off-heap.size: "40 mb"
#    taskmanager.memory.jvm-overhead.min: "30 mb"
#    taskmanager.memory.jvm-metaspace.size: "50 mb"
#    taskmanager.memory.off-heap.size: "20 mb"
    taskmanager.memory.task.heap.size: "100 mb"
#    taskmanager.memory.network.min: "20 mb"
#    taskmanager.memory.framework.heap.size: "20 mb"
#    taskmanager.memory.framework.off-heap.size: "20 mb"
    state.backend.fs.checkpointdir: file:///checkpoints/flink/checkpoints
    state.checkpoints.dir: file:///checkpoints/flink/externalized-checkpoints
    state.savepoints.dir: file:///checkpoints/flink/savepoints
  jobManagerConfig:
    systemMemoryFraction: 0.2
    resources:
      requests:
        memory: "1Gi"
        cpu: "0.2"
    replicas: 1
  taskManagerConfig:
    taskSlots: 2
    systemMemoryFraction: 0.5
    resources:
      requests:
        memory: "2Gi"
        cpu: "0.2"
#      limits:
#        memory: "500Mi"
  volumeMounts:
    - mountPath: /checkpoints
      name: checkpoints
  volumes:
    - name: checkpoints
      hostPath:
        path: /tmp/checkpoints
        type: Directory
  flinkVersion: "1.11"
  deploymentMode: Dual
  jarName: "operator-test-app-1.0.0-SNAPSHOT.jar"
  parallelism: 3
  entryClass: "com.lyft.OperatorTestApp"
