apiVersion: flink.k8s.io/v1beta1
kind: FlinkApplication
metadata:
  name: operator-test-app
  annotations:
  labels:
    environment: development
spec:
  image: flink-test-app:local.1
  imagePullPolicy: Never
  imagePullSecrets:
    - name: dockerhub
  flinkConfig:
    state.backend.fs.checkpointdir: file:///checkpoints/flink/checkpoints
    state.checkpoints.dir: file:///checkpoints/flink/externalized-checkpoints
    state.savepoints.dir: file:///checkpoints/flink/savepoints
    env.java.opts.jobmanager: "-XX:+UseG1GC"
  jobManagerConfig:
    systemMemoryFraction: 0.2
    resources:
      requests:
        memory: "400Mi"
        cpu: "0.2"
      limits:
        memory: "800Mi"
        cpu: "0.2"
    replicas: 1
  taskManagerConfig:
    taskSlots: 2
    systemMemoryFraction: 0.5
    resources:
      requests:
        memory: "800Mi"
        cpu: "0.2"
      limits:
        memory: "800Mi"
        cpu: "0.2"
  volumeMounts:
    - mountPath: /checkpoints
      name: checkpoints
  volumes:
    - name: checkpoints
      hostPath:
        path: /tmp/checkpoints
        type: Directory
  flinkVersion: "1.11"
  deploymentMode: Dual
  jarName: "operator-test-app-1.0.0-SNAPSHOT.jar"
  parallelism: 2
  entryClass: "com.lyft.OperatorTestApp"
