{{- if .Values.serviceAccounts.flink.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flink.serviceAccountName" . }}
  namespace: {{ .Values.namespaces.jobNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "flink-operator.name" . }}
    helm.sh/chart: {{ include "flink-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    team-owner: {{ .Values.teamOwner }}
{{- end }}
