operatorImageName: lyft/flinkk8soperator
operatorVersion: v0.5.0
imagePullPolicy: IfNotPresent

nameOverride: flink-operator

appName: flink

teamOwner: detection

namespaces:
  jobNamespace: ""

rbac:
  create: false

serviceAccounts:
  flink:
    create: false
    name: 
  flinkoperator:
    create: false
    name: flinkoperator

resourceRequests:
  memory: "1Gi"
  cpu: 1

resourceLimits:
  memory: "46Gi"
  cpu: 5

# Comma separated list of namespaces that the operator is configured to watch
# Empty string by default, which indicates all namespaces will be watched
resyncPeriod: "15s"
workers: 16
maxErrDuration: "60m"

organization: 

role: ppd-infra-spot

additionalLabels:
  team-owner: detection

podmonitor:
  enabled: true

accountId:

region:

tag: