operatorImageName: lyft/flinkk8soperator
operatorVersion: v0.4.0
imagePullPolicy: IfNotPresent

rbac:
  create: true

flinkJobNamespace: default

serviceAccounts:
  flink:
    create: true
    name:
  flinkoperator:
    create: true
    name:

resourceRequests:
  memory: 1G
  cpu: 0.5

resourceLimits:
  memory: 1G
  cpu: 2

# Comma separated list of namespaces that the operator is configured to watch
# Empty string by default, which indicates all namespaces will be watched
limitNamespace: ""
resyncPeriod: "30s"
metricsPrefix: "flinkk8soperator"
profilerPort: "10254"
ingressUrlFormat: ""
useKubectlProxy: false
proxyPort: "8001"
containerNameFormat: ""
workers: 4
baseBackoffDuration: "100ms"
maxBackoffDuration: "30s"
maxErrDuration: "5m"
