%% This file can be compiled into blue_green_state_machine.png by installing mermaidjs (https://mermaidjs.github.io/) and running
%% mmdc -i blue_green_state_machine.mmd -o blue_green_state_machine.png -w 1732 -b transparent

graph LR
New --> ClusterStarting

subgraph RunningGroup [Running]
Running
DeployFailed
end

subgraph UpdatingGroup [Updating]
Running --> Updating
Updating --> ClusterStarting
DeployFailed --> Updating

ClusterStarting -- savepoint disabled --> SubmittingJob
ClusterStarting -- savepoint enabled --> Savepointing
ClusterStarting -- Create fails --> DeployFailed

Savepointing --> SubmittingJob
Savepointing -- Savepoint fails --> Recovering

Recovering --> SubmittingJob
Recovering -- No externalized checkpoint --> RollingBackJob

SubmittingJob -- first deploy --> Running
SubmittingJob -- updating existing application --> DualRunning
SubmittingJob -- job start fails --> RollingBackJob
RollingBackJob --> DeployFailed

DualRunning -- tearDownVersionHash set --> Running
DualRunning -- tear down fails --> DeployFailed
end

linkStyle 4 stroke:#303030
linkStyle 5 stroke:#303030
linkStyle 6 stroke:#FF0000
linkStyle 8 stroke:#FF0000
linkStyle 10 stroke:#FF0000
linkStyle 11 stroke:#303030
linkStyle 12 stroke:#303030
linkStyle 13 stroke:#FF0000
linkStyle 14 stroke:#FF0000
linkStyle 15 stroke:#303030
linkStyle 16 stroke:#FF0000